CREATE TABLE T_NOTICIA (
    ID_NOTICIA BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    NOTICIA LONGTEXT NOT NULL,
    CVE_USUARIO_ALTA VARCHAR(20) NOT NULL,
    STP_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CVE_USUARIO_MODIFICA VARCHAR(20),
    STP_MODIFICA TIMESTAMP,
    CVE_USUARIO_BAJA VARCHAR(20),
    STP_BAJA TIMESTAMP
);

CREATE TABLE T_IMAGEN_NOTICIA (
    ID_IMAGEN_NOTICIA BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_NOTICIA BIGINT UNSIGNED,
    NOM_IMAGEN VARCHAR(250),
    REF_UID VARCHAR(250),
    CVE_USUARIO_ALTA VARCHAR(20) NOT NULL,
    STP_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CVE_USUARIO_MODIFICA VARCHAR(20),
    STP_MODIFICA TIMESTAMP,
    CVE_USUARIO_BAJA VARCHAR(20),
    STP_BAJA TIMESTAMP
);
